name: csukuangfj-sherpa-onnx-paraformer-zh-2023-03-28

on:
  push:
    branches:
      - download

  workflow_dispatch:

jobs:
  csukuangfj-sherpa-onnx-paraformer-zh-2023-03-28:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/sherpa-onnx-paraformer-zh-2023-03-28
          rm -rf sherpa-onnx-paraformer-zh-2023-03-28/.git
          tar cjvf sherpa-onnx-paraformer-zh-2023-03-28.tar.bz2 sherpa-onnx-paraformer-zh-2023-03-28

      - name: Release sherpa-onnx-paraformer-zh-2023-03-28
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: sherpa-onnx-paraformer-zh-2023-03-28.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: asr-models
