name: csukuangfj-sherpa-ncnn-conv-emformer-transducer-2022-12-06-chinese-english

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  ncnn-csukuangfj-sherpa-ncnn-conv-emformer-transducer-2022-12-06-chinese-english:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/sherpa-ncnn-conv-emformer-transducer-2022-12-06
          rm -rf sherpa-ncnn-conv-emformer-transducer-2022-12-06/.git

          sudo apt-get install -y tree

          tree ./sherpa-ncnn-conv-emformer-transducer-2022-12-06
          ls -lh ./sherpa-ncnn-conv-emformer-transducer-2022-12-06
          tar cjvf ./sherpa-ncnn-conv-emformer-transducer-2022-12-06.tar.bz2 sherpa-ncnn-conv-emformer-transducer-2022-12-06

      - name: Release sherpa-ncnn-conv-emformer-transducer-2022-12-06
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: sherpa-ncnn-conv-emformer-transducer-2022-12-06.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-ncnn
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: models
