name: csukuangfj-sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  ncnn-csukuangfj-sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13
          rm -rf sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/.git

          sudo apt-get install -y tree

          tree ./sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13
          ls -lh ./sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13

          tar cjvf sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13.tar.bz2 sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13

      - name: Release sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-ncnn
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: models
