name: csukuangfj-sherpa-onnx-en-wenet-librispeech

on:
  push:
    branches:
      - download

  workflow_dispatch:

jobs:
  onnx-en-wenet-librispeech:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/sherpa-onnx-en-wenet-librispeech
          rm -rf sherpa-onnx-en-wenet-librispeech/.git

          sudo apt-get install -y tree

          tree ./sherpa-onnx-en-wenet-librispeech
          ls -lh ./sherpa-onnx-en-wenet-librispeech

      - uses: actions/upload-artifact@v3
        with:
          name: sherpa-onnx-en-wenet-librispeech
          path: sherpa-onnx-en-wenet-librispeech
