name: csukuangfj-sherpa-onnx-zh-wenet-wenetspeech

on:
  push:
    branches:
      - download
      - small-fixes
  workflow_dispatch:

jobs:
  onnx-zh-wenet-wenetspeech:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/sherpa-onnx-zh-wenet-wenetspeech
          rm -rf sherpa-onnx-zh-wenet-wenetspeech/.git

          sudo apt-get install -y tree

          tree ./sherpa-onnx-zh-wenet-wenetspeech
          ls -lh ./sherpa-onnx-zh-wenet-wenetspeech

      - uses: actions/upload-artifact@v3
        with:
          name: sherpa-onnx-zh-wenet-wenetspeech
          path: sherpa-onnx-zh-wenet-wenetspeech
