name: onnx

on:
  push:
    branches:
      - small-fixes

  workflow_dispatch:

jobs:
  onnx:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Download model
        shell: bash
        run: |
          d=sherpa-onnx-paraformer-zh-2023-09-14
          # GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/$d
          d=sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01
          git clone https://www.modelscope.cn/pkufool/${d}.git

          cd $d
          git lfs pull --include "*.onnx"
          rm -rf ./.git

          rm -f ./.gitattributes ./.done

          ls -lh

          cd ..

          sudo apt-get install -y tree

          tree ./$d
          ls -lh ./$d
          tar cjvf ./$d.tar.bz2 $d

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: kws-models
