name: onnx

on:
  push:
    branches:
      - small-fixes

  workflow_dispatch:

jobs:
  onnx:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Download model
        shell: bash
        run: |
          d=sherpa-onnx-paraformer-zh-2023-09-14
          # GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/$d
          GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/zrjin/icefall-asr-mdcc-zipformer-2024-03-11
          d=icefall-asr-mdcc-zipformer-2024-03-11

          pushd $d/exp
          git lfs pull --include "*.onnx"
          popd
          dst=sherpa-onnx-zipformer-cantonese-2024-03-13
          mkdir $dst

          mv -v $d/exp/*.onnx $dst/
          mv -v $d/test_wavs $dst/
          mv -v $d/data/lang_char/tokens.txt $dst/
          d=$dst

          # rm -rf ./.git

          # rm -f ./.gitattributes ./.done

          ls -lh

          # cd ..

          sudo apt-get install -y tree

          tree ./$d
          ls -lh ./$d
          tar cjvf ./$d.tar.bz2 $d

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: asr-models
