name: onnx

on:
  push:
    branches:
      - small-fixes

  workflow_dispatch:

jobs:
  onnx:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Download model
        shell: bash
        run: |
          d=k2fsa-zipformer-bilingual-zh-en-t
          # GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/$d
          git clone https://huggingface.co/csukuangfj/$d

          dst=sherpa-onnx-streaming-zipformer-small-bilingual-zh-en-2023-02-16
          mkdir $dst
          cp $d/data/lang_char_bpe/bpe.model $dst
          cp $d/data/lang_char_bpe/tokens.txt $dst

          cp $d/exp/32/*.onnx $dst/
          mkdir -p $dst/64
          mkdir -p $dst/96

          cp $d/exp/64/*.onnx $dst/64/
          cp $d/exp/96/*.onnx $dst/96/

          cp $d/data/lang_char_bpe/bpe.model $dst/64/
          cp $d/data/lang_char_bpe/tokens.txt $dst/64/

          cp $d/data/lang_char_bpe/bpe.model $dst/96/
          cp $d/data/lang_char_bpe/tokens.txt $dst/96/

          sudo apt-get install -y tree
          d=$dst

          tree ./$d
          ls -lh ./$d
          tar cjvf ./$d.tar.bz2 $d

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: asr-models
