name: onnx

on:
  push:
    branches:
      - small-fixes

  workflow_dispatch:

jobs:
  onnx:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download model
        if: false
        shell: bash
        run: |
          GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/icefall-tts-aishell3-vits-low-2024-04-06
          src=icefall-tts-aishell3-vits-low-2024-04-06

          cd $src
          cd data
          git lfs pull --include rule.far
          cd ../exp
          git lfs pull --include *.onnx
          mv vits-epoch-960.onnx model.onnx

          cd ../../

          dst=vits-icefall-zh-aishell3

          mkdir -p $dst

          cp -v $src/data/*.fst $dst/
          cp -v $src/data/*.txt $dst/
          cp -v $src/data/*.far $dst/

          cp -v $src/exp/*.onnx $dst/

          d=$dst

          sudo apt-get install -y tree

          tree ./$d
          ls -lh ./$d
          tar cjvf ./$d.tar.bz2 $d
          ls -lh

      - name: Download model
        if: false
        shell: bash
        run: |
          GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/icefall-asr-librispeech-streaming-zipformer-small-2024-03-18
          src=icefall-asr-librispeech-streaming-zipformer-small-2024-03-18

          dst=sherpa-onnx-streaming-zipformer-ctc-small-2024-03-18
          mkdir -p $dst

          cp -v $src/exp-ctc-rnnt-small/*.onnx $dst/
          cp -v $src/data/lang_bpe_500/bpe.model $dst/
          cp -v $src/data/lang_bpe_500/words.txt $dst/
          cp -v $src/data/lang_bpe_500/lexicon.txt $dst/
          cp -v $src/data/lang_bpe_500/tokens.txt $dst/
          cp -v $src/data/lang_bpe_500/HLG.fst $dst/
          cp -v $src/README.md $dst/
          cp -va $src/test_wavs $dst/

          d=$dst

          sudo apt-get install -y tree

          tree ./$d
          ls -lh ./$d
          tar cjvf ./$d.tar.bz2 $d
          ls -lh


      - name: Download model
        if: false
        shell: bash
        run: |
          d=sherpa-onnx-conformer-zh-stateless2-2023-05-23
          # GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/$d
          git clone https://huggingface.co/csukuangfj/$d
          rm -rf $d/.git
          rm -rf $d/.gitattributes
          ls -lh $d

          sudo apt-get install -y tree

          tree ./$d
          ls -lh ./$d
          tar cjvf ./$d.tar.bz2 $d

      - name: Download model
        if: false
        shell: bash
        run: |
          d=sherpa-onnx-punct-ct-transformer-zh-en-vocab272727-2024-04-12
          # GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/$d
          git clone https://huggingface.co/csukuangfj/$d
          rm -rf $d/.git
          rm -rf $d/.gitattributes
          ls -lh $d

          sudo apt-get install -y tree

          tree ./$d
          ls -lh ./$d
          tar cjvf ./$d.tar.bz2 $d

      - name: Download model
        if: true
        shell: bash
        run: |
          # d=sherpa-onnx-zipformer-small-audio-tagging-2024-04-15
          d=sherpa-onnx-zipformer-audio-tagging-2024-04-09
          # GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/$d
          git clone https://huggingface.co/k2-fsa/$d
          rm -rf $d/.git
          rm -rf $d/.gitattributes
          ls -lh $d

          sudo apt-get install -y tree

          tree ./$d
          ls -lh ./$d
          tar cjvf ./$d.tar.bz2 $d

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: audio-tagging-models
          # tag: punctuation-models
