name: onnx

on:
  push:
    branches:
      - small-fixes

  workflow_dispatch:

jobs:
  onnx:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Download model
        shell: bash
        run: |
          d=sherpa-onnx-conformer-zh-stateless2-2023-05-23
          # GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/$d
          git clone https://huggingface.co/csukuangfj/$d
          rm -rf $d/.git
          rm -rf $d/.gitattributes
          ls -lh $d

          sudo apt-get install -y tree

          tree ./$d
          ls -lh ./$d
          tar cjvf ./$d.tar.bz2 $d

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: asr-models
