name: vits-piper-de_DE

on:
  push:
    branches:
      - vits-piper-de-DE
  workflow_dispatch:

jobs:
  vits-piper-de_DE:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }} ${{ matrix.type }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: eva_k
            type: x_low
          - name: karlsson
            type: low
          - name: kerstin
            type: low
          - name: pavoque
            type: low
          - name: ramona
            type: low
          - name: thorsten
            type: low
          - name: thorsten
            type: medium
          - name: thorsten
            type: high
          - name: thorsten_emotional
            type: medium

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate model
        shell: bash
        run: |
          cd .github/scripts
          export NAME=${{ matrix.name }}
          export TYPE=${{ matrix.type }}
          ./vits-piper-de_DE.sh

      - name: Collect files
        shell: bash
        run: |
          export NAME=${{ matrix.name }}
          export TYPE=${{ matrix.type }}
          dst=vits-piper-de_DE-$NAME-$TYPE
          mkdir $dst

          cp -v .github/scripts/*.onnx*  $dst
          cp -v .github/scripts/tokens.txt $dst
          cp -v .github/scripts/MODEL_CARD  $dst
          cp -v .github/scripts/vits-piper-de_DE.sh  $dst
          cp -v .github/scripts/vits-piper-de_DE.py  $dst
          mv .github/scripts/espeak-ng-data $dst/
          tar cjfv ${dst}.tar.bz2 $dst
          ls -lh $dst

      - name: Release to sherpa-onnx
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: vits-piper-*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: tts-models

      - name: upload model to huggingface
        shell: bash
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          NAME: ${{ matrix.name }}
          TYPE: ${{ matrix.type }}
        run: |
          ls -lh
          git clone https://huggingface.co/csukuangfj/vits-piper-de_DE-$NAME-$TYPE huggingface
          rm -rf huggingface/*

          git config --global user.email "csukuangfj@gmail.com"
          git config --global user.name "Fangjun Kuang"

          src=vits-piper-de_DE-$NAME-$TYPE
          cp -a $src/* huggingface/
          cd huggingface
          ls -lh
          git lfs track "cmn_dict"
          git lfs track "ru_dict"

          git status
          git add .
          git commit -m "update" || true
          git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/vits-piper-de_DE-$NAME-$TYPE main || true
