name: vits-cantonese-hf-xiaomaiiwn

on:
  push:
    branches:
      - download
      - small-fixes2
  workflow_dispatch:

jobs:
  vits-cantonese-hf-xiaomaiiwn:
    runs-on: ubuntu-latest
    name: Cantonese
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Convert model ${{ matrix.name }}
        shell: bash
        run: |
          cd .github/scripts
          ../scripts/vits-cantonese-hf-xiaomaiiwn.sh

      - name: collect results
        shell: bash
        run: |
          cd .github/scripts

          name=${{ matrix.name }}
          dst=vits-cantonese-hf-xiaomaiiwn
          mkdir $dst
          cp -v *.onnx $dst
          cp -v lexicon.txt $dst
          cp -v tokens.txt $dst
          cp -v ./vits-cantonese-hf-xiaomaiiwn.sh $dst
          cp -v ./vits-cantonese-hf-xiaomaiiwn.py $dst

          cd $dst
          wget -q https://huggingface.co/csukuangfj/vits-zh-aishell3/resolve/main/rule.fst
          cd ..

          tar cjfv ${dst}.tar.bz2 $dst
          mv ${dst}.tar.bz2 ../..

      - name: Release to sherpa-onnx
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: vits-cantonese-hf-xiaomaiiwn*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: tts-models

      - name: upload model to huggingface
        shell: bash
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          NAME: ${{ matrix.name }}
        run: |
          cd .github/scripts
          ls -lh
          git clone https://huggingface.co/csukuangfj/vits-cantonese-hf-xiaomaiiwn
          cd vits-cantonese-hf-xiaomaiiwn
          cp ../*.onnx .
          cp ../*.json .
          cp ../lexicon.txt .
          cp ../tokens.txt .

          wc -l lexicon.txt

          tail lexicon.txt

          rm -fv rule*
          wget -q https://huggingface.co/csukuangfj/vits-zh-aishell3/resolve/main/rule.fst

          git config --global user.email "csukuangfj@gmail.com"
          git config --global user.name "Fangjun Kuang"

          git status
          git add .
          ls -lh

          git commit -m "update"
          git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/vits-cantonese-hf-xiaomaiiwn main

          cd ..
          rm -rf vits-cantonese-hf-xiaomaiiwn/.git
          mv vits-cantonese-hf-xiaomaiiwn ../..
          cd ../..
          sudo apt-get install -y tree
          tree ./vits-cantonese-hf-xiaomaiiwn
          ls -lh ./vits-cantonese-hf-xiaomaiiwn

      - uses: actions/upload-artifact@v3
        with:
          name: vits-cantonese-hf-xiaomaiiwn
          path: vits-cantonese-hf-xiaomaiiwn
