name: vits-vctk

on:
  push:
    branches:
      - download
      - small-fixes
  workflow_dispatch:

jobs:
  vits-vctk:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate model
        shell: bash
        run: |
          cd .github/scripts
          mkdir vits-vctk
          cd vits-vctk
          cp ../*.onnx .
          cp ../tokens.txt .
          cp ../lexicon.txt .
          cd ..
          tar cvjf vits-vctk.tar.bz2 ./vits-vctk
          mv -v ./vits-vctk.tar.bz2 ../..

      - name: Release vctk
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: *.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: tts-models

      - name: Collect files
        shell: bash
        run: |
          cd .github/scripts
          ./vits.sh

      - name: upload model to huggingface
        shell: bash
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          NAME: ${{ matrix.name }}
          TYPE: ${{ matrix.type }}
        run: |
          cd .github/scripts
          ls -lh
          git clone https://huggingface.co/csukuangfj/vits-vctk
          cd vits-vctk
          cp ../*.onnx .
          cp ../tokens.txt .
          cp ../lexicon.txt .

          git config --global user.email "csukuangfj@gmail.com"
          git config --global user.name "Fangjun Kuang"

          git status
          git add .
          git commit -m "update"
          git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/vits-vctk main
          cd ..



      - name: Download model
        if: false
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/vits-vctk
          rm -rf vits-vctk/.git
          rm -v vits-vctk/*.pth

          sudo apt-get install -y tree
          tree ./vits-vctk
          ls -lh ./vits-vctk

      - uses: actions/upload-artifact@v3
        if: false
        with:
          name: vits-vctk
          path: vits-vctk
