name: vits-piper-en_GB

on:
  push:
    branches:
      - vits-piper-en-gb
  workflow_dispatch:

jobs:
  vits-piper-en_GB:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }} ${{ matrix.type }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: alan
            type: low
          - name: alan
            type: medium
          - name: alba
            type: medium
          - name: aru
            type: medium
          - name: jenny_dioco
            type: medium
          - name: northern_english_male
            type: medium
          - name: semaine
            type: medium
          - name: southern_english_female
            type: low
          - name: vctk
            type: medium
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate model
        shell: bash
        run: |
          cd .github/scripts
          export NAME=${{ matrix.name }}
          export TYPE=${{ matrix.type }}
          ./vits-piper-en_GB.sh

      - name: Collect files
        shell: bash
        run: |
          export NAME=${{ matrix.name }}
          export TYPE=${{ matrix.type }}
          dst=vits-piper-en_GB-$NAME-$TYPE
          mkdir $dst

          cp -v .github/scripts/tokens.txt  $dst
          cp -v .github/scripts/*.onnx*  $dst
          cp -v .github/scripts/MODEL_CARD  $dst
          cp -v .github/scripts/vits-piper-en_GB.sh $dst
          cp -v .github/scripts/vits-piper-en_GB.py $dst
          mv .github/scripts/espeak-ng-data $dst/
          tar cjfv ${dst}.tar.bz2 $dst
          ls -lh $dst

      - name: Release to sherpa-onnx
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: vits-piper-*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: tts-models

      - name: upload model to huggingface
        shell: bash
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          NAME: ${{ matrix.name }}
          TYPE: ${{ matrix.type }}
        run: |
          ls -lh
          git clone https://huggingface.co/csukuangfj/vits-piper-en_GB-$NAME-$TYPE huggingface

          git config --global user.email "csukuangfj@gmail.com"
          git config --global user.name "Fangjun Kuang"

          src=vits-piper-en_GB-$NAME-$TYPE
          cp -a $src/* huggingface/
          cd huggingface
          ls -lh
          git lfs track "cmn_dict"
          git lfs track "ru_dict"

          git status
          git add .
          git commit -m "update" || true
          git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/vits-piper-en_GB-$NAME-$TYPE main || true
