name: vits-mms

on:
  push:
    branches:
      - small-fixes2
  workflow_dispatch:

# See
# https://dl.fbaipublicfiles.com/mms/misc/language_coverage_mms.html

jobs:
  vits-coqui:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: deu
          - name: eng
          - name: fra
          - name: rus
          - name: spa
          - name: tha
          - name: ukr
          - name: nan

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate model
        shell: bash
        run: |
          cd .github/scripts
          export NAME=${{ matrix.name }}
          ./vits-mms.sh

      - name: Collect files
        shell: bash
        run: |
          export name=${{ matrix.name }}
          dst=vits-mms-$name
          mkdir $dst

          cp -v .github/scripts/README.md $dst
          cp -v .github/scripts/tokens.txt $dst
          cp -v .github/scripts/*.onnx $dst
          cp -v .github/scripts/*.json $dst
          cp -v .github/scripts/vits-mms.sh $dst
          cp -v .github/scripts/vits-mms.py $dst
          tar cjfv ${dst}.tar.bz2 $dst
          ls -lh $dst

      - name: Release to sherpa-onnx
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: vits-mms-*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: tts-models

      - name: upload model to huggingface
        shell: bash
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          NAME: ${{ matrix.name }}
        run: |
          git config --global user.email "csukuangfj@gmail.com"
          git config --global user.name "Fangjun Kuang"

          ls -lh
          src=vits-mms-$NAME
          echo "src: $src"

          git clone https://huggingface.co/csukuangfj/$src huggingface
          rm -rf huggingface/*

          cp -a $src/* huggingface/
          cd huggingface
          ls -lh

          git status
          git add .
          git commit -m "update" || true
          git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/$src main || true
